# First stage: build the application
FROM 3.9.7-eclipse-temurin-17 AS build
COPY . /app
WORKDIR /app
RUN mvn package -DskipTests
  
  # Second stage: create a slim image
FROM openjdk:17-jre-slim
COPY --from=build /app/target/my-application.jar /app.jar
ENTRYPOINT ["java", "-jar", "/app.jar"]