spring:
  application:
    name: "vagas"
  datasource:
    url: jdbc:postgresql://localhost:5446/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8081

springdoc:
  api-docs.path: /v3/api-docs
  swagger-ui.path: /swagger-ui.html

api:
  security:
    token:
      secret: vbGbyCB2MDWPM7HNjK4UaRHaeHPSUBSu
#Host: postgres
#Port: 5432
#db: postgres
#user: postgres
#pasword: postgres

#sem keycloak
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: ${ISSUER_URL:http://localhost:9999/realms/test-realm}
